### PR TITLE
fix: symphony 2.5.x compatibility

### PR DESCRIPTION
**Pull request by pani-c**
fix: symphony 2.5.x compatibility
added: as usebility improvement always remove last "/" in redirect url

### CODE REVIEW

**Comment by michael-e** [comment]
If possible, please send separate pull requests for each topic. At least, please provide separate commits for formatting fixes, compatibility work and feature changes. This makes it much simpler to pull and/or discuss the improvements.

Addtionally, I don't understand why you remove the trailing slash of the redirect URL. Honestly , the comment in the code doesn't make much sense:

> Remove last "/", just in case it is missing in the redirect url input

**Comment by nitriques** [comment]
>  I don't understand why you remove the trailing slash of the redirect URL

I do not either. And please be careful with whitespace changes as it makes diffs hard to read.

I would be ok with everything in this (https://github.com/pani-c/mobiledevicedetection/commit/d4026346d7a796ed281e2aab47b2ce3b7f20c5e3?w=0), whitout whitespace changes and without the rtrim call.

**Comment by pani-c** [comment]
> If possible, please send separate pull requests for each topic.

Sounds logical. Sorry!

> And please be careful with whitespace changes

Noticed this right after the commint. The editor saved the file with new line endings etc. Sorry therefore, too!

> I don't understand why you remove the trailing slash

I thought, as mentioned somewhere in the forum discussion, removing the last slash of the redirect URL entered in the preferences input and of the URL it is compared to might be more user freindly. Someone might forget the trailing slash in the redirect field, which would lead to an error. In my case it doesn't matter. Hope that makes sense.

**Comment by nitriques** [comment]
>  it is compared to might be more user freindly.

Symphony already appends the a trailling / if there is not... Still does not understand what it solves.

**Comment by michael-e** [comment]
> The editor saved the file with new line endings etc.

It looks to me as if the line endings are messed up in the original code, and your editor fixed that. Nevertheless, please try to have a separate commit for it.

Regarding the trailing slash: I don't know what has been discussed in the forum, but IMHO the extension shouldn't try to be clever by changing the redirect URL. (If a URL has a traling slash, it will be perfect for Symphony; and if there is no trailing slash, Symphony will perform a redirect to the trailing slash variant.)

**Comment by pani-c** [comment]
I'll recommit the changes separately shortly!

Again regarding the trailing slash: As far as I understand it the problem is how the extension handles the redirects. Currently it checks if the current page url equals the redirect url and redirects until this condition is met. If the trailing slash is missing in the redirect url input you'll likely get an error as this condition is never met.

Nevertheless. I'll provide it as a separate commit as it just "works" for me. But maybe I just did something wrong in the first place :-)

**Comment by michael-e** [comment]
I think I finally understand the trailing slash issue. `$current` will always have a trailing slash, because `getCurrentPage()` always appends a slash, see `/symphony/lib/boot/func.utilities.php`.

I wonder if [this line](https://github.com/pani-c/mobiledevicedetection/blob/d4026346d7a796ed281e2aab47b2ce3b7f20c5e3/extension.driver.php#L137) was intended to deal with this. Isn't it just the wrong way 'round? Maybe you can try `strpos($current, $redirect) !== 0` and see if that solves the issue without any further modifications.

Unfortunately I can not test it, because I never used this extension. So I don't know the drawbacks, nor do I have a website to test it properly.

**Comment by nitriques** [comment]
I would be able to test it since I have an old 2.4 site that uses it (for backward compat)

@pani-c Also please create the PR against the [integration branch](https://github.com/symphonists/mobiledevicedetection/tree/integration) please :smile: :rocket: 

I'll leave this PR open for now, but feel free to close it when you'll send the new PR. Thanks!

**Comment by firegoby** [comment]
@michael-e - Thanks for looking into that, just to let you know I can confirm that on my 2.5.2 installation switching the arguments to `strpos($current, $redirect) !== 0` (and commenting out the new `rtrim($url, "/")` line on #151) got the extension working just right for me. Many thanks all!

**Comment by pani-c** [comment]
New pull request are comming this weekend! 
@firegoby I've also checked that and will add the changes to the pull requests.

I had the flu and needed some time off...

I am closing this now and will open new requests as **nitriques** suggested.

**Comment by nitriques** [comment]
Thanks!

**Pull request closed without merging**
